### ISSUE TITLE
Update emailjs dependency

### ISSUE THREAD

**Issue by ivan-kleshnin** [wavded/winston-mail#16]
I'm getting `TypeError: msecs must be a number` at basic example with **winston-mail**. 
Problem exists with **emailjs@0.3.4** and disappears with **emailjs@0.3.12**. 

Full stack, if you care:
```
TypeError: msecs must be a number
    at Object.exports.enroll (timers.js:156:11)
    at Socket.setTimeout (net.js:329:12)
    at new SMTPResponse (~/demo/node_modules/winston-mail/node_modules/emailjs/smtp/response.js:66:11)
    at Object.exports.monitor (~/demo/node_modules/winston-mail/node_modules/emailjs/smtp/response.js:71:9)
    at Object.SMTP.connect (~/demo/node_modules/winston-mail/node_modules/emailjs/smtp/smtp.js:172:35)
    at Object.Client._connect (~/demo/node_modules/winston-mail/node_modules/emailjs/smtp/client.js:68:17)
    at Object.Client._poll (~/demo/node_modules/winston-mail/node_modules/emailjs/smtp/client.js:28:18)
    at ~/demo/node_modules/winston-mail/node_modules/emailjs/smtp/client.js:102:21
    at Object.Message.valid (~/demo/node_modules/winston-mail/node_modules/emailjs/smtp/message.js:134:10)
    at Object.Client.send (~/demo/node_modules/winston-mail/node_modules/emailjs/smtp/client.js:83:14)
```

**Comment by wavded** [comment]
@ivan-kleshnin care to make a pull request?
