### ISSUE TITLE
Can't remove the transport

### ISSUE THREAD

**Issue by endquote** [wavded/winston-mail#32]
```
var winston = require('winston');
require('winston-mail').Mail;
winston.add(winston.transports.Mail, { to: 'com@net.org' });
winston.remove(winston.transports.Mail);
```

```
C:\Users\josh\Downloads\node_modules\winston\lib\winston\logger.js:527
    throw new Error('Transport ' + name + ' not attached to this instance');
    ^

Error: Transport undefined not attached to this instance
    at Logger.remove (C:\Users\josh\Downloads\node_modules\winston\lib\winston\logger.js:527:11)
    at Object.winston.(anonymous function) [as remove] (C:\Users\josh\Downloads\node_modules\winston\lib\winston.js:87:34)
    at Object.<anonymous> (C:\Users\josh\Downloads\test.js:6:9)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

winston 2.1.1
winston mail 1.0.0
node 4.2.3

**Comment by endquote** [comment]
Using `winston.remove('mail');` seems to work. However according to the docs [here](https://github.com/winstonjs/winston/blob/master/README.md#using-the-default-logger), it seems like my code above should work too.

**Comment by wavded** [comment]
Sorry don't know.  Seems like an issue for the main winston project as I'm not sure how they handle loading and or unloading plugins.

**Comment by wavded** [comment]
Closing do to age.  Discussion can continue if still an issue.
